# Generated by Django 6.0.1 on 2026-01-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': 'blogs'},
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_blog_body',
            new_name='blog_body',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_featured_img',
            new_name='featured_image',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_is_featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_short_description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='blog_title',
            new_name='title',
        ),
    ]
