# Generated by Django 6.0.1 on 2026-01-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_options_rename_blog_author_blogs_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='aupdated_at',
            new_name='updated_at',
        ),
    ]
